### ISSUE TITLE
images

### ISSUE THREAD

**Issue by regis-g** [regisg495/programa-estagio-aiko#1]

**Comment by regis-g-dev** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/41974237/88269018-b1a2d780-cca9-11ea-8322-f6f3d3d96952.png)
![Screenshot_1](https://user-images.githubusercontent.com/41974237/88270093-7e614800-ccab-11ea-844d-d66fe89d83e5.png)
![Screenshot_3](https://user-images.githubusercontent.com/41974237/88270235-b1a3d700-ccab-11ea-8abb-03fa36dac225.png)
![Screenshot_4](https://user-images.githubusercontent.com/41974237/88270310-d304c300-ccab-11ea-8a00-832adbb40194.png)

![Screenshot_5](https://user-images.githubusercontent.com/41974237/88270439-08a9ac00-ccac-11ea-906e-3eea8249af23.png)
![Screenshot_6](https://user-images.githubusercontent.com/41974237/88270627-4c9cb100-ccac-11ea-83a0-8d9a6cd35e66.png)
![Screenshot_7](https://user-images.githubusercontent.com/41974237/88271605-c2ede300-ccad-11ea-95f4-590dbdd13387.png)
Vei
